microsoft/vscode-azureresourcegroups

- extension.bundle.ts
- package-lock.json
- package.json
- package.nls.json
- src/commands/registerCommands.ts
- src/commands/tags/AzExtFileSystem.ts
- src/commands/tags/TagFileSystem.ts
- src/commands/tags/editTags.ts
- src/commands/tags/getTagDiagnostics.ts
- src/commands/tags/registerTagDiagnostics.ts
- src/extension.ts
- src/extensionVariables.ts
- src/tree/ResourceGroupTreeItem.ts
- test/getTagDiagnostics.test.ts
I implemented a pared down version of VS Code's `FileSystemProvider` that only supports editing single files (aka no read directory, etc.). This should hopefully replace `AzureBaseEditor` in the UI package - I'll do that once I make sure this works for at least one other scenario (probably App Service since I think that's the only thing using `AzureBaseEditor` at the moment).
I went the file system route because I think it's easier to view/edit tags in a file than a wizard and it felt like displaying tags in the tree would clutter it up too much. Users still get basic validation in the form of standard VS Code problems:
I plan to support editing tags on resources in a future PR.
> Add support for editing tags on resource groups 🏷

- src/commands/deleteResourceGroup.ts
- src/commands/tags/TagFileSystem.ts
- src/tree/ResourceGroupTreeItem.ts
For the `deletedRg` message, I decided against a notification for it. We already have the message that we started deleting it. Once it starts, do people care when it finishes? Personally I don't. So anyways I thought the output window was enough.
Fixes #22 
Fixes #2
> Add a few lines to output

- package.json
- package.nls.json
- src/tree/ResourceGroupTreeItem.ts
Modeled after the portal:
Unfortunately I don't know all the types that should be hidden, but I figured I'd at least start with the types I saw on my subscription
> Hide some resource types

- src/commands/revealResource.ts
These are showing up as `<REDACTED: user-file-path>`
> Hopefully fix resourceType telemetry

- README.md
- package.json
- package.nls.json
- src/AzExtWrapper.ts
- src/azureExtensions.ts
- src/commands/helpAndFeedback/getStarted.ts
- src/commands/helpAndFeedback/reportIssue.ts
- src/commands/helpAndFeedback/reviewIssues.ts
- src/commands/registerCommands.ts
- src/commands/revealResource.ts
- src/extension.ts
- src/extensionVariables.ts
- src/tree/HelpTreeItem.ts
And make the extension a bit more generic to prepare for being a dependency of other Azure extensions
- "Resources" instead of "Resource Groups"
- Collapse both views by default
> Add "Help and Feedback" view

- src/commands/deleteResourceGroup.ts
Resource group names are already case-insensitive when _creating_, plus this matches the portal.
Fixes https://github.com/microsoft/vscode-azureresourcegroups/issues/42
> Be case-insensitive when confirming delete of resource group

- src/tree/GroupTreeItemBase.ts
- src/tree/ResolvableTreeItemBase.ts
- src/tree/ResourceGroupTreeItem.ts
- src/tree/SubscriptionTreeItem.ts
Since the leaf nodes actually have the SubscriptionTreeItem as their parent, I had to implement `removeChildFromCache`. The implementation will remove the child from the cache of any GroupTreeItemBase that has the child cached. I had to use some internal properties/methods like `refreshUIOnly` and `removeChildFromCache`, so we might need to expose those.
Other changes:
* Fixed loadMoreChildrenImpl `this` bug (see comment in code)
* Removed unused `items` instance variable on `GroupTreeItemBase`.
> Fix deleting app resource tree items

- src/tree/ResolvableTreeItemBase.ts
Without this getter, descriptions present on the resolvedResult are never propagated up to the actual tree item. We may have to do this with some other properties in the future. Probably iconPath
> Fix descriptions for leaf tree items

- src/commands/createResource.ts
- src/constants.ts
- src/utils/ExtensionActivationManager.ts
ex:
```json
"contributes": {
"x-azResources": {
"activation": {
"onFetch": [
"microsoft.web/staticsites"
]
},
"commands": [
{
"command": "staticWebApps.createStaticWebApp",
"title": "%staticWebApps.createStaticWebApp%",
"type": "microsoft.web/staticsites"
}
]
}
}
```
> Use same contributes key for commands and activation

- src/utils/azureUtils.ts
Was investigating an error I was getting trying to open storage blobs. Figured out that [`findTreeItem`](https://github.com/microsoft/vscode-azuretools/blob/d38498f0085deb912675e4d2cb376f973c12f31e/utils/src/tree/AzExtTreeDataProvider.ts#L261) is case sensitive and the fullIds were different only by the casing of `resourceGroups`.
`/subscriptions/843d979b-47f8-4bb9-9fbc-33e33962c304/resourcegroups/funcbasic1a9cbd88f7`
`/subscriptions/843d979b-47f8-4bb9-9fbc-33e33962c304/resourceGroups/funcbasic1ab151b770/...`
I'm not really sure how this is happening because I would think that if we `.toLowerCase()` it in one place, how could it be upper case when we search for it? But I must not be understanding something right because it works when I removed `.toLowerCase()`
> Don't make GroupTreeItem ids lower case

- src/tree/AppResourceTreeItem.ts
For simplicity, I was just making the parent be the Subscription node since it was convenient for some tree actions.  We might have to be careful with some commands now (such as `deleteTreeItem`) because when deleted, it only removes it from the cache of the direct parent which means it likely won't be deleted from the subscription node's array of resources.  A refresh should hit the API again though, so it should be okay because we refresh whenever they change the grouping.
> Fix `findTreeItem` by correctly linking `AppResourceTreeItem` to `GroupTreeItem`

- package.json
- package.nls.json
- src/api.d.ts
- src/commands/explorer/groupBy.ts
- src/commands/registerCommands.ts
- src/resolvers/NoopResolver.ts
- src/resolvers/ShallowResourceResolver.ts
I like this icon, but I'm open to suggestions.
Also made the Noop and Shallow resolver have `collapsibleState: TreeItemCollapsibleState.None`
> Use context menu for Group By setting and make some resolvers not collapsible

- src/tree/SubscriptionTreeItem.ts
Delete is now handled properly without this function because the subscription is no longer the parent to all app resources
> Delete unneeded function

- src/api.d.ts
- src/utils/ExtensionActivationManager.ts
Based on https://github.com/microsoft/vscode-azureresourcegroups/pull/146#discussion_r838925631. If an extension is installed that would have already been activated by the activation manager (had it been installed), then we should immediately activate it.
> Activate newly installed extensions immediately

- package-lock.json
- package.json
- src/commands/installExtension.ts
- src/commands/registerCommands.ts
- src/resolvers/InstallableAppResourceResolver.ts
Edited `InstallableAppResourceResolver` to improve the installation UX. Now it returns a node with a single child instructing users to install the associated extension.
To handle install, I'm calling `extension.open` and `workbench.extensions.installExtension` so that the marketplace page and the installation modal open together. I think opening both is better than opening one or the other.
We might need to add more logic later to handle if an extension is installed but disabled.
> Improve install extension experience

- src/commands/tags/TagFileSystem.ts
- src/tree/AppResourceTreeItem.ts
- src/tree/ResourceGroupTreeItem.ts
- src/tree/SubscriptionTreeItem.ts
Fetches ResourceGroup data using the SDK to enable all the commands on resource group group tree items.
The implementation isn't the prettiest, but I made it as fast as we can until we add a something like a global resource cache. As of now, we fetch a list of all resource groups when the subscription is refreshed. Since I never await the promise, it seems to have a very minimal (if any), impact on the tree performance.
> Fix resource groups

- src/tree/SubscriptionTreeItem.ts
All resource groups only showed 1 child, if any
> Fix resource groups only having 1 child

- package-lock.json
- package.json
- src/AzExtWrapper.ts
- src/resolvers/OutdatedAppResourceResolver.ts
- src/tree/ResolvableTreeItemBase.ts
I was going to do something fancier with semver, but I ended up just checking for the existence of the `x-azResources` key in the extension manifest. IMO this is way simpler and more fool-proof, and we can easily update the `meetsMinVersion()` function later if needed.
> Handle outdated extensions

- package.json
- package.nls.json
- src/commands/deleteResourceGroup/deleteResourceGroup.ts
Hiding the refresh workspace command from palette:
* Fixes #192
Delete resource group from command palette:
* Fixes #193 
* Fixes #194
Note: the delete resource group command will still fail when the groupBy setting != resourceGroup, I will file a new issue for this if needed. #199
> Fix a few small issues

- package-lock.json
- package.json
- src/api/AzureResourceGroupsExtensionApi.ts
- src/api/pickAppResource.ts
- src/commands/openInPortal.ts
- src/commands/tags/editTags.ts
- src/commands/viewProperties.ts
- src/extension.ts
- src/tree/GroupTreeItemBase.ts
- src/tree/SubscriptionTreeItem.ts
- src/utils/azureUtils.ts
This is a big step forward in terms of helping us solve all of the issues surrounding running commands from the palette. The design of showTreeItemPicker doesn't fit well into the new model, and so this is just a slight variation that skips a step.
Depends on https://github.com/microsoft/vscode-azuretools/pull/1141
There are a few options we can take advantage of here:
```ts
export interface PickAppResourceOptions extends IAzureQuickPickOptions {
type?: string; // ex: 'microsoft.web/sites'
expectedChildContextValue?: string | RegExp | (string | RegExp)[]; // ex: EnvironmentTreeItem.contextValue
}
```
If you pass in `type`, the picks are filtered based on that type. Passing a value for `expectedChildContextValue` enables us to select children of app resources, ex: an app setting tree item. …
> Implement pickAppResource

- package-lock.json
- package.json
- src/tree/AppResourceTreeItem.ts
This prevents `GroupTreeItem.refreshImpl` from being called every time it gets created. I don't believe this is expected behavior.
I'm also unsure if the `this should actually be "resolve"` comment still holds up
> Refresh UI only to prevent extra calls to refreshImpl

- package-lock.json
- package.json
- src/commands/deleteResourceGroup/deleteResourceGroup.ts
- src/tree/ResourceGroupTreeItem.ts
Fixes #308 
Deriving the number of resources in a resource group from the cached children (or a similar source like the treeMap) results in the number being wrong unless view is grouped by resource group and the subscription tree item has been expanded.
It's much simpler to just fetch the list of resources and use that.
> Fetch resources to get number of resources in RG

- package-lock.json
- package.json
- src/commands/registerCommands.ts
- src/tree/HelpTreeItem.ts
> Add open walkthrough tree item to help view

- src/azureExtensions.ts
The version bot better shut up on this one 😠 
Just commenting out the azureExtension part of it.  The icons/labels will still be in there. Shouldn't be an issue, makes it look better but it's also only seen if the hiddenStacks is enabled anyway.
> Remove container app resource types from resolvers

- package.json
- src/tree/GroupTreeItemBase.ts
- src/tree/ResourceGroupTreeItem.ts
- src/tree/SubscriptionTreeItem.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/1096
When "refresh" is triggered on the root or a parent, it will only call its refresh, and then call `loadMoreChildren` on itself.  However, because `loadMoreChildrenImpl` doesn't actually create new tree items (since we are caching all of the `AppResourceTreeItems`), refreshing the root, the subscription, and the groups didn't actually do anything.
By adding `refreshImpl` to `SubscriptionTreeItem` and `GroupTreeItemBase`, the `AppResourceTreeItems` will actually get refreshed now and it'll be a meaningful refresh.
I can't fix the root level refresh without affecting performance because if I call refresh in `SubscriptionTreeItem.loadMoreChildrenImpl`, it will activate all of the extensions at once. 
The root level refresh …
> When sub or group is refreshed, refresh the children as well

- package.json
- package.nls.json
- src/commands/registerCommands.ts
Fixes https://github.com/microsoft/vscode-azurestorage/issues/1046
> Fix Workspace view loadMore

- .vscode/launch.json
- src/azureExtensions.ts
- src/utils/azureUtils.ts
Needed to make sure extensions that haven't updated to use the `AzExtResourceType` context value yet will still be able to add the proper context menus to the group tree items.
We made this change in https://github.com/microsoft/vscode-azureresourcegroups/pull/337, but forgot to consider this breaking change.
> Support legacy resource types

- src/azureExtensions.ts
This is needed since we won't be releasing RGs before storage, see https://github.com/microsoft/vscode-azurestorage/pull/1140/files.
> Add storage to legacy type map

- src/azureExtensions.ts
- src/utils/azureUtils.ts
Since we're releasing storage without the legacy context types, we can remove it from the legacy map.
The labels were messed up for a few resource group types. If a AzExtResourceType exists, but doesn't have a display name, just display the provider type. If it doesn't, then display the "unknown" label on the resource group.
> Remove storage from legacy map and fix "Unknown" labels

- src/api/v2/DefaultApplicationResourceProvider.ts
- src/api/v2/ResourceGroupsExtensionManager.ts
- src/api/v2/v2AzureResourcesApi.ts
- src/api/v2/v2AzureResourcesApiImplementation.ts
- src/api/v2/v2AzureResourcesApiWrapper.ts
- src/constants.ts
- src/extension.ts
- src/tree/GroupTreeItemBase.ts
- src/tree/ResourceCache.ts
- src/tree/SubscriptionTreeItem.ts
- src/tree/v2/ResourceBranchDataProviderManagerBase.ts
- src/tree/v2/application/ApplicationResourceBranchDataProviderManager.ts
- src/tree/v2/application/ApplicationResourceGroupingManager.ts
- src/tree/v2/application/ApplicationResourceTreeDataProvider.ts
- src/tree/v2/application/DefaultApplicationResourceItem.ts
- src/tree/v2/application/GroupingItem.ts
- src/tree/v2/application/SubscriptionItem.ts
- src/tree/v2/application/registerResourceGroupsTreeV2.ts
- src/tree/v2/workspace/WorkspaceResourceBranchDataProviderManager.ts
Updates the V2 API and implementation to use "normalized" resource types (i.e. `AzExtResourceType`) for branch data provider registration (which follows how V1 currently operates). Previously, the Azure resource type was used which is not ideal as both type and kind(s) are needed to totally distinguish between Azure resources.
Also updates the grouping logic to better replicate the existing V1 behavior in terms of hidden types, static resource type groups, and sorting.
Also removes the notion of IDs when registering resource providers, as they weren't used.  Extensions can now indicate that they contribute application/workspace resources using a `"resources": true` property within the `application` or `workspace` property.  (The thinking was that, in the future, if we need more complex …
> Use normalized resource types for registration

- src/api/v2/v2AzureResourcesApi.ts
- src/tree/v2/BranchDataProviderItem.ts
- src/tree/v2/GenericItem.ts
- src/tree/v2/ResourceGroupsItem.ts
- src/tree/v2/ResourceGroupsItemCache.ts
- src/tree/v2/ResourceTreeDataProviderBase.ts
- src/tree/v2/application/DefaultApplicationResourceBranchDataProvider.ts
- src/tree/v2/application/DefaultApplicationResourceItem.ts
- src/tree/v2/application/GroupingItem.ts
- src/tree/v2/application/SubscriptionItem.ts
Allow BDPs to provide an ID for their items, which can then be accumulated to represent a "path" through the tree.
Every application/workspace item will have an ID of some sort.  BDPs can provide IDs but, if omitted, reasonable default IDs will be chosen (e.g. application resource items will use their Azure resource IDs, generic items will use their label, all others will be assigned a unique ID.)
The `ResourceGroupsItemCache` can be used to generate item "paths" (an array that contains the IDs of each item in the tree, in order, from the root item to the item in question) via `getPathForItem()` or retrieve the item represented by a path via `getItemForPath()`.
> Model for providing branch data provider item IDs

- src/api/pickAppResource.ts
- src/api/v2/v2AzureResourcesApi.ts
- src/api/v2/v2AzureResourcesApiImplementation.ts
- src/api/v2/v2AzureResourcesApiWrapper.ts
- src/extension.ts
- src/extensionVariables.ts
- src/tree/v2/application/registerResourceGroupsTreeV2.ts
- src/tree/v2/workspace/registerWorkspaceTreeV2.ts
* Exposing the workspace and application tree data providers so they can be used by client extensions.
* Some cleanup and renaming around the registration functions
> Expose `TreeDataProvider`s in API

- src/tree/v2/ResourceTreeDataProviderBase.ts
Calling `this.onDidChangeTreeDataEmitter.fire([])` with an empty array doesn't actually refresh the whole tree.
> Actually refresh whole tree

- src/api/v2/compatibility/CompatibleBranchDataProvider.ts
- src/api/v2/compatibility/CompatibleBranchDataProviderBase.ts
Relies on https://github.com/microsoft/vscode-azuretools/pull/1254.
In order to no longer use `AzExtTreeDataProvider.refresh()` in the client extensions, we need to be able to signal a refresh to the branch data provider from the client extension resolvers.
This is working towards removing direct usages of the `AzExtTreeDataProvider` in the client extensions.
> Add refresh capabilities to `CompatibleBranchDataProvider`

- src/api/v2/DefaultApplicationResourceProvider.ts
- src/api/v2/ResourceProviderManagers.ts
- src/api/v2/v2AzureResourcesApi.ts
- src/api/v2/v2AzureResourcesApiImplementation.ts
- src/api/v2/v2AzureResourcesApiWrapper.ts
- src/tree/v2/BranchDataProviderItem.ts
- src/tree/v2/application/ApplicationResourceTreeDataProvider.ts
- src/tree/v2/application/SubscriptionItem.ts
- src/tree/v2/workspace/WorkspaceResourceTreeDataProvider.ts
Updates to the V2 API based on feedback from the design discussion.
Notes:
- I experimented with allowing models to be `unknown`, but it cascades that uncertainty throughout the rest of the API and implementation. While allowing models to be simple types represents the ultimate in flexibility, I feel like extension developers would almost certainly *never* do this in practice.  As soon as any model needs to carry extra information along with it (or, say, want to conform to the optional properties of the API), moving from simple types to objects would likely be a significant refactor.  It simply makes sense for the models to be objects (even if simple ones).
> V2 API Updates per Design Discussion Feedback

- gulpfile.ts
- package-lock.json
- package.json
In the spirit of web-ifying the extension, this removes the dependency on `fs-extra`.  (In actuality it was only used by the build process, so could just be switched to a dev-dependency but, in any case, is easily replaced by built-in runtime APIs.)
> Remove dependency on fs-extra.

- package.json
- src/api/v2/v2AzureResourcesApi.ts
- src/commands/openInPortal.ts
- src/tree/v2/BranchDataProviderItem.ts
- src/tree/v2/application/ApplicationResourceTreeDataProvider.ts
- src/tree/v2/application/GroupingItem.ts
- src/utils/v2/credentialsUtils.ts
The Resource Groups extension now exposes an "Open in Portal" command for all application resources.  BranchDataProvider's have the option to override that portal URL.  The command is also exposed if any child of an application resource sets the optional `ApplicationResourceModel.portalUrl` property.
Command for application resources without a registered BDP:
Command for application resources with a registered BDP:
Command for arbitrary children that expose the `portalUrl` property:
> Expose and implement "Open in Portal" for application resources

- package.json
- src/api/v2/ResourceProviderManagers.ts
- src/tree/v2/workspace/WorkspaceResourceTreeDataProvider.ts
So, it bothers me when nothing is shown in the (V2) workspace view as I can never be sure it is intentional or not.  VS Code has the ability to show "welcome views" when tree views are otherwise empty.  This change adds welcome views for the workspace view that differ when:
- No workspace is open
- No workspace resources were enumerated
- No workspace resource providers are registered (i.e. no extension that registers a provider is installed)
- Resources were enumerated (i.e. the traditional view)
The text content is mostly a placeholder at this point; I'd appreciate some "PM wordsmithing".  In particular, would it make sense to try to point users somewhere, for example, when no resource providers have been installed?
> WIP: (V2) Workspace Welcome Views

- src/AzExtWrapper.ts
- src/tree/v2/GenericItem.ts
- src/tree/v2/application/DefaultApplicationResourceBranchDataProvider.ts
- src/tree/v2/application/DefaultApplicationResourceItem.ts
Brings back the RG V1 behavior where the application resource view would prompt the user to install extensions known to manage an enumerated resource type, if that extension was not yet installed.
> Bring back suggested extension installation

- src/api/v2/v2AzureResourcesApi.ts
- src/api/v2/v2AzureResourcesApiImplementation.ts
- src/api/v2/v2AzureResourcesApiWrapper.ts
Expose the `registerActivity()` function from the V2 API. This eliminates the need for extensions to obtain references to both V1 and V2 APIs.
> Expose registerActivity() from V2 API.

- src/tree/v2/ResourceGroupsItem.ts
- src/tree/v2/ResourceGroupsItemCache.ts
- src/tree/v2/ResourceTreeDataProviderBase.ts
- src/tree/v2/application/DefaultApplicationResourceItem.ts
- src/tree/v2/application/GroupingItem.ts
- src/tree/v2/application/SubscriptionItem.ts
- src/utils/v2/getApplicationResourceId.ts
Cherry-picked non-compatibility related changes from #418.
Changed how we cache child -> parent relations. Instead of a map, I'm storing a reference to the parent on the child item itself. This way, no cache modification can accidentally remove a reference.
> Make tree item ids mimic Azure ids

- src/tree/v2/BranchDataProviderItem.ts
We've been using semicolons so far, so it's probably best to keep using them.
> Separate contexts with semicolons

- src/tree/v2/application/ApplicationResourceItem.ts
- src/tree/v2/application/GroupingItem.ts
- src/tree/v2/application/registerResourceGroupsTreeV2.ts
Context https://github.com/microsoft/vscode-azureresourcegroups/pull/358#discussion_r1019549830
This makes it so that Application resource items all have the `resource` property defined and set to the `ApplicationResource`. Children will not have this property and will be instances of the base `BranchDataProviderItem`, while application resources will be `ApplicationResourceItem`s.
The `resource` property is needed by [QuickPickAppResourceStep](https://github.com/microsoft/vscode-azuretools/pull/1229/files#diff-d3a273a1f6a314889469732205ab9e72bb6664b6c344f89e60b2f0269cbf32edR19-R31)
> Add `ApplicationResourceItem`

- src/tree/v2/ResourceGroupsItemCache.ts
- src/tree/v2/ResourceTreeDataProviderBase.ts
- src/tree/v2/application/ApplicationResourceTreeDataProvider.ts
I think this better fits here, than `findByIdExperience` in utils. For now, we'll only use this method for V1.5 extension compatibility and will not expose this in the V2 API.
> Add `findItemById` to ResourceGroups TDP

- src/AzExtWrapper.ts
- src/api/v2/DefaultApplicationResourceProvider.ts
- src/api/v2/ResourceProviderManagers.ts
- src/api/v2/v2AzureResourcesApi.ts
- src/api/v2/v2AzureResourcesApiImplementation.ts
- src/api/v2/v2AzureResourcesApiWrapper.ts
- src/commands/deleteResourceGroup/v2/deleteResourceGroupV2.ts
- src/commands/viewProperties.ts
- src/extension.ts
- src/tree/v2/BranchDataProviderItem.ts
- src/tree/v2/azure/AzureResourceBranchDataProviderManager.ts
- src/tree/v2/azure/AzureResourceGroupingManager.ts
- src/tree/v2/azure/AzureResourceItem.ts
- src/tree/v2/azure/AzureResourceTreeDataProvider.ts
- src/tree/v2/azure/DefaultApplicationResourceItem.ts
- src/tree/v2/azure/DefaultAzureResourceBranchDataProvider.ts
- src/tree/v2/azure/GroupingItem.ts
- src/tree/v2/azure/SubscriptionItem.ts
- src/tree/v2/azure/registerResourceGroupsTreeV2.ts
- src/utils/v2/credentialsUtils.ts
Renaming all `Application___` things to `Azure___`. Since we're pretty sure resources in the Azure view will continue to be Azure-only.
I considered using Remote instead of Azure in the names, but went with Azure in the end.
Suggested in https://github.com/microsoft/vscode-azuretools/pull/1229#discussion_r1013281223
> Rename Application things to Azure things

- package-lock.json
- package.json
- src/api/v2/compatibility/CompatibleAzExtTreeDataProvider.ts
- src/extension.ts
- src/extensionVariables.ts
- src/tree/v2/azure/registerAzureTree.ts
- src/tree/v2/workspace/registerWorkspaceTree.ts
I found that I separate this class from the rest of the compatibility code easily. Figured it's worth it to reduce the size of #358. I will probably keep trying to apply the changes in #358 in separate smaller PRs like this.
Merging this PR should reduce #358 to a more reasonable size. 
Brandon and I worked on this code together, so it'd be good to get a final review from another source.
> Add `CompatibleAzExtTreeDataProvider`

- src/api/v2/compatibility/workspace/CompatibilityWorkspaceResourceProvider.ts
In #449 we made it so `getResources` is called for each open workspace folder, and once with undefined as an argument for system-level resources.
For compatibility, we'll only return resources when undefined is passed.
> Don't provide duplicate resources

- package.json
- src/commands/registerCommands.ts
- src/extension.ts
- src/extensionVariables.ts
- src/tree/v2/ResourceTreeDataProviderBase.ts
- src/tree/v2/azure/AzureResourceTreeDataProvider.ts
- src/tree/v2/azure/registerAzureTree.ts
- src/tree/v2/workspace/WorkspaceResourceTreeDataProvider.ts
- src/tree/v2/workspace/registerWorkspaceTree.ts
Two changes:
1. Allow refreshing a single tree item instead of the entire tree everywhere. This means changing the `Event<void>` to `Event<void | ResourceGroupsItem | ResourceGroupsItem[] | null | undefined>` everywhere.
2. Split the Azure view refresh command in two. One that refreshes the entire tree, ignoring any selected nodes. This makes the refresh button on the Azure view title behave like it has in the past. The new command is `refreshAzureItem`, intended for the context menus of items in the Azure view.
> Refresh individual tree items, and fix refresh title button

- package-lock.json
- package.json
- src/commands/tags/TagFileSystem.ts
- src/commands/tags/editTags.ts
- src/tree/AppResourceTreeItem.ts
- src/tree/ResourceGroupTreeItem.ts
- src/tree/v2/azure/AzureResourceItem.ts
Depends on https://github.com/microsoft/vscode-azuretools/pull/1257
I will add support for editing tags on resource groups in a follow up PR.
Also, I need to add a `dontUnwrap` flag to `appResourceExperience` in utils so to support getting an item from the picker here.
> v2 edit tags command for resources

- src/tree/v2/ResourceBranchDataProviderManagerBase.ts
- src/tree/v2/azure/GroupingItem.ts
- src/tree/v2/azure/registerAzureTree.ts
- src/tree/v2/workspace/WorkspaceResourceTreeDataProvider.ts
Before this change:
When a BDP was registered we refreshed the entire tree. A case where this becomes super annoying is if you have expanded the Azure Functions group but then expand another group, say App Service. The App Service extension will activate and register a BDP. The whole tree is then refreshed, including the Function Apps.
After this change:
Group items listen for changes to the registered BDPs. They will refresh when the BDP registered for a type (`AzExtResourceType`) they care about changes. The types they care about are the set of types of the group children.
For the Workspace tree, the refresh behavior remains the same. On any changes to registered BDPs, the whole tree will refresh. This is still needed for now since the client-controlled tree items are root tree items.
> Don't refresh entire tree on add/remove BDP

- src/api/v2/compatibility/CompatibleBranchDataProviderBase.ts
- src/commands/revealResource.ts
Note that this currently doesn't support revealing subscriptions or resource groups, only resources. I hope to be able to modify this function to support them in a future PR.
Working towards https://github.com/microsoft/vscode-azureresourcegroups/issues/479
> Implement `revealResource` for v2

- src/tree/v2/ResourceTreeDataProviderBase.ts
- src/tree/v2/azure/registerAzureTree.ts
- src/tree/v2/createTreeView.ts
- src/tree/v2/workspace/WorkspaceResourceTreeDataProvider.ts
- src/tree/v2/workspace/registerWorkspaceTree.ts
- src/tree/v2/wrapTreeForVSCode.ts
Fixes #487 
Context:
Inside resource groups we wrap items provided by branch data providers to add some properties we use internally. The wrapper items are given to VS Code. We have to keep a map of the branch items to the wrapper items. This is so we can translate branch items to resource group items.
One place where we translate branch items to wrapper resource groups items is when a branch data provider fires the onDidChangeTreeData event. We have to translate the event data from branch items to wrapper items, and then pass the wrapper items to VS Code.
Bug cause:
When we use the tree data provider to pick a tree item, the branch item cache is cleared. It’s currently cleared when getChildren is called and undefined is passed. As a result, when onDidChangeTreeData is fired with a branch …
> Only clear cache when VS Code calls `getChildren(undefined)`

- src/commands/openInPortal.ts
- src/tree/v2/BranchDataProviderItem.ts
- src/tree/v2/azure/AzureResourceItem.ts
- src/tree/v2/workspace/WorkspaceResourceTreeDataProvider.ts
The thinking is...
`BranchDataProvider`s provide `BranchDataItem`s, which are wrapped up in `BranchDataItemWrapper`s, which are owned by RG. 
\- Brandon
@nturinski just want you to take a look at the PR description.
> Rename `BranchDataProviderItem` to `BranchDataItemWrapper`

- src/api/compatibility/pickAppResource.ts
- src/extension.ts
- src/tree/BranchDataItemCache.ts
- src/tree/azure/registerAzureTree.ts
- src/tree/createTreeView.ts
Fixes #487 
See [my comment](https://github.com/microsoft/vscode-azureresourcegroups/issues/487#issuecomment-1376616009) for why this issue happens, and why this fix is needed.
With v1, client extensions expected items returned by pickAppResource to be the same item as what might be on the tree. To fulfill this expectation in v2, after an item is picked we try to translate it into an item that was created by the tree.
> Translate items created via picker into items created via tree

- package-lock.json
- package.json
We require Node 16.13.0, which was introduced in 1.66. See https://code.visualstudio.com/updates/v1_66#_engineering
Fixes #403
> Update minimum required version of VS Code to 1.66

- src/commands/revealResource.ts
- src/tree/ResourceTreeDataProviderBase.ts
- src/tree/azure/AzureResourceTreeDataProvider.ts
Fixes a bug where nothing was happening when I was calling for a resource to be revealed
> Don't do case-sensitive Azure resource ID comparison

- src/tree/ResourceBranchDataProviderManagerBase.ts
When a BDP does a root refresh, don't refresh the entire tree.
Instead, this refreshes any item which has a child that is provided by said BDP.
> Scoped global refresh for BDPs

- src/api/compatibility/application/CompatibleApplicationResourceTreeItem.ts
We need to call refresh when a tree item calls removeChildFromCache on the parent. That way the removed items actually go away.
Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/783
I tested with VMs, but fix should apply to all extensions equally.
> Fix `AzExtTreeItem.deleteTreeItem` compat

- src/api/compatibility/application/CompatibleApplicationResourceBranchDataProvider.ts
- src/api/compatibility/application/CompatibleApplicationResourceTreeItem.ts
v1.5 client extension expect this node to have `id` defined. Specifically, they use it to create portal urls for child nodes.
Fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/785
> Define `id` on Azure resource nodes to fix children open in portal

- .github/workflows/api-extractor.yaml
- .github/workflows/api-publish.yaml
- api/.npmignore
- api/README.md
Also changed the image links on the readme to point to the GitHub raw files, instead of relative paths. That way the readme can have images without publishing the images in the package.
> Add GitHub Actions workflows for api package

- src/tree/InvalidItem.ts
- src/tree/ResourceTreeDataProviderBase.ts
- src/tree/azure/GroupingItem.ts
- src/tree/workspace/WorkspaceResourceTreeDataProvider.ts
I'm keeping `InvalidItem` very simple for now. However, I can see us adding features like "Copy error information" command to it in the future.
> Gracefully handle tree errors with `InvalidItem`

- src/commands/installExtension.ts
This will allow us to get some useful insights about how often users are installing an extension from the "Install extension to enable additional features..." tree item.
> Report if extension was installed via command

- extension.bundle.ts
- src/api/createWrappedAzureResourcesExtensionApi.ts
- src/tree/ResourceBranchDataProviderManagerBase.ts
- src/utils/wrapFunctionsInTelemetry.ts
- test/wrapFunctionsInTelemetry.test.ts
Errors thrown inside the wrapped functions were not being handled in this scope, so they weren't being recorded in telemetry.
To make sure the errors are handled inside the `callWithTelemetryAndErrorHandling`, we gotta await stuff.
> Actually throw errors in wrapFunctionsInTelemetry

- package.json
- webpack.config.js
Should solve the issue we're seeing with `edit tags` in #543
I'm using the `node-stdlib-browser` package as a dev dependency to help us bring in Node's `Buffer` library, let me know if there is another package or method we would prefer using instead to solve this issue.
> Add `Buffer` Node standard library to `webpack` bundle

- src/tree/workspace/WorkspaceResourceTreeDataProvider.ts
This error handling is now covered centrally by https://github.com/microsoft/vscode-azureresourcegroups/blob/43ea37f416779b5b6c0e7945e36850c402cee7cc/src/tree/ResourceBranchDataProviderManagerBase.ts#L81-L87
> Remove redundant workspace getResourceItem error handling

- package.json
- src/tree/workspace/WorkspaceResourceTreeDataProvider.ts
Instead of not displaying resources if no workspace is opened, show resources and also add a tree item that prompts users to open a folder/workspace.
This more closely mirrors the current behavior, and fixes https://github.com/microsoft/vscode-azurestorage/issues/1214
> Show workspace resources even if workspace isn't open

- .azure-pipelines/common/build.yml
- package-lock.json
- package.json
- src/commands/accounts/logIn.ts
- src/commands/accounts/logOut.ts
- src/commands/accounts/selectSubscriptions.ts
- src/extension.ts
- src/extensionVariables.ts
- src/services/AzureSubscriptionProvider.ts
- src/services/DesktopSubscriptionProvider.ts
- src/services/SubscriptionProvider.ts
- src/services/WebAzureSubscriptionProvider.ts
- src/tree/azure/AzureResourceTreeDataProvider.ts
Refactor VS Code auth portion of the vscode.dev work to hide the auth implementation details from the rest of the code. Now both the VS Code auth (used in vscode.dev) and the Azure Account API auth are shoehorned into a common interface.
This makes it easier to adapt for testing purposes and is similar to what I've done in https://github.com/microsoft/vscode-azureresourcegroups/pull/563
> Refactor VS Code auth

- src/commands/registerCommands.ts
> Refresh subscription instead of group

- src/commands/createResourceGroup.ts
Fixes #627 
Though unless there's an Azure prefix, we're not supposed to capitalize the resources, so I went the other direction and fixed "Create resource group"
> Change message of create resource group

- src/api/compatibility/pickAppResource.ts
- src/extension.ts
- src/tree/BranchDataItemCache.ts
- src/tree/BranchDataProviderItem.ts
- src/tree/ResourceTreeDataProviderBase.ts
- src/tree/azure/AzureResourceItem.ts
Fixes #640, and a bunch of others including:
* "Cannot read properties of undefined (reading 'createClient')" errors.
* Issues related to things not being refreshed on the tree after running a command from the palette.
This following line was added in https://github.com/microsoft/vscode-azureresourcegroups/pull/510 as a band aid solution to try and fix issues where the item returned by the picker was not reference equal to the same item in the tree view. This made it so calling refresh with the item didn't refresh on the tree among other things.
https://github.com/microsoft/vscode-azureresourcegroups/blob/11e06179ad12c30fb01259bbe8bfc0a87304c8eb/src/api/compatibility/pickAppResource.ts#L19
The fix in #510 only worked sometimes, as seen by the numerous bugs reported by CTI surrounding …
> Only keep one object per id cached

- package.json
- package.nls.json
- src/commands/registerCommands.ts
- src/tree/azure/AzureResourceTreeDataProvider.ts
Fixes the bug Alex mentioned in triage where sub filter was grayed out on desktop.
Also removed duplicate commands because the treeDataProvider handles that for us now.
If I don't have the conditions for the logIn and logOut commands to show up in the command palette, we'll get double in VS Code desktop due to the Azure Account extension also contributing commands.
> Consolidate login, logout, and selectSub commands

- src/tree/azure/AzureResourceTreeDataProvider.ts
Fixes https://github.com/microsoft/vscode-azureresourcegroups/issues/643
The Account extension is just opening a url for the `createAccount` command. We can just by-pass that and open the url similar to how we do for creating a student account. 
https://github.com/microsoft/vscode-azure-account/blob/14d1d7e84b964742716fba224d032010ff3f1800/src/extension.ts#L167
> Replace azure-account call with openUrl

- .azure-pipelines/common/package.yml
Fixes builds with the same build number from different pipelines overwriting each other.
> Add Build.DefinitionName to published web bits path

- src/api/DefaultAzureResourceProvider.ts
- src/services/AzureResourcesService.ts
Splitting out changes from #563 to make that PR smaller.
These changes make it so the default Azure resource provider uses an `AzureResourcesService` for actually listing the resources. This way the underlying `AzureResourcesService` can be changed out for testing with a service that returns mock resources.
> Make Azure resource provider mockable

- src/api/compatibility/registerApplicationResourceResolver.ts
- src/extension.ts
- src/extensionVariables.ts
These were used in v1 but are not longer needed.
> Remove unused events and emitters

- src/api/compatibility/CompatibleAzExtTreeDataProvider.ts
Fixes https://github.com/microsoft/vscode-azureappservice/issues/2421
> Set `treeDataProvider` on subscription returned by `showTreeItemPicker`

- package.json
We are currently using ExP flights to ensure that no user sees more than one walkthrough, which is not a long-term solution. Disabling this walkthrough so we can roll the azd walkthrough out to 100% of users and turn off the experiment.
> Disable resource group walkthrough

- src/commands/registerCommands.ts
- src/tree/azure/FocusViewTreeDataProvider.ts
Originally added to make the focus/unfocus operations snappier. Was causing more problems than it was worth.
Fixes https://github.com/microsoft/vscode-azureresourcegroups/issues/688, https://github.com/microsoft/vscode-azureresourcegroups/issues/694
> Stop caching resource list in focus view

- api/CHANGELOG.md
- api/docs/vscode-azureresources-api.d.ts
- api/src/resources/azure.ts
- src/commands/viewProperties.ts
A small change that extends the existing `ViewPropertiesModel` to allow async loading of properties. It is backwards compatible and requires no changes to client extensions. Client extensions can optionally utilize this feature once this API change is released in the extension.
This change is required so that we can stop making so many requests in `getResourceItem` for top level resources and decrease loading times.
> api: Extend `ViewPropertiesModel` to allow async loading of properties

- .eslintrc.js
- src/commands/focus/focusGroup.ts
- src/commands/viewProperties.ts
- src/extensionVariables.ts
- src/tree/azure/FocusViewTreeDataProvider.ts
- src/tree/azure/grouping/ResourceTypeGroupingItem.ts
Fixing where we were importing from the types file meant for documentation only. I also added an eslint rule to prevent this in the future.
We should only import this stuff from the src itself.
> Stop importing from docs

- src/api/DefaultAzureResourceProvider.ts
This method was moved to the API package so it can be more easily updated...but one of the import sites was missed (and it was the one I needed apparently).
> Update import of `getAzExtResourceType`

- src/tree/azure/AzureResourceTreeDataProvider.ts
Sometimes users might be signed in, but all their subscriptions exist under a tenant that isn't authenticated yet. In this case, they need to use the Sign In to Directory command.
This change makes it so that if these conditions are both true:
A. User has no subscriptions under the currently authenticated tenants
B. User has unauthenticated tenants
Then we show the "Sign In to Directory..." command in the tree instead of the "Select subscriptions..." command.
> Prompt users to sign in to a directory

- src/tree/azure/AzureResourceTreeDataProvider.ts
The Azure Account extension is no longer used by the Azure Resources extension and the `updateSubscriptionsAndTenants` event it had is relied upon to generate Azure-subscription-related telemetry. We need to mimic the old event so that Kusto queries can be minimally changed.
> Add telemetry for subscription information

- package-lock.json
- package.json
We'll release this as 0.8.0, but for CTIs testing it's nice to have it match so I'll bump it before I give them the RC.
> Bump version to 0.8.0-alpha

- CHANGELOG.md
- src/tree/azure/grouping/AzureResourceGroupingManager.ts
Fixes #819 
This bug occurs when a deleted or nonexistent resource is returned by the Azure REST API by mistake. Previous behavior is that no resource groups were displayed, now all resources are displayed and an error is logged in the console.
The error looks like
`
2024-02-13 13:21:44.375 [error] Error creating grouping item for key: "RGNAME-rg" Internal error: Expected value to be neither null nor undefined: resourceGroup for grouping item
`
> Fix bug that prevents resource groups from loading when there's a ghost resource

- main.js
- package.json
- src/api/compatibility/application/CompatibleApplicationResourceBranchDataProvider.ts
- src/utils/wrapFunctionsInTelemetry.ts
Mitigates https://github.com/microsoft/vscode-azurefunctions/issues/3851 and other issues, I'm sure
We see this error floating around quite often. While this doesn't actually fix it, at least the error makes a little more sense to the user.
> Throw an error for any item that resolves as undefined

- package-lock.json
- package.json
- src/api/compatibility/AzureResourceGroupsExtensionApi.ts
- src/extension.ts
- src/tree/azure/AzureResourceTreeDataProviderBase.ts
- test/api/v1.test.ts
Relies on https://github.com/microsoft/vscode-azuretools/pull/1703
I was trying to add a `getSubscription` function on the provider itself, but for some reason, `getAzureSubscriptionProvider` kept throwing an error, saying that it wasn't a function. 🤷
I'm okay with my current solution, but was really confused as to why it wasn't working.
> Add listSubscriptions to resourceApi

- src/api/compatibility/AzureResourceGroupsExtensionApi.ts
- test/api/v1.test.ts
We wanted to bump the API version for minor updates that aren't breaking, but bumping the version from 0.0.1 to 0.0.2 requires updating all of the requested versions in each extension. This outweighs the purpose of bumping for minor changes. Next time we create breaking changes to this API, we will update it to 1.0.0 so in the future we can bump the minor version and avoid this.
The mistake we made was starting the API at 0.0.1 instead of 1.0.0.
> Change internal RGs API version back to 0.0.1

- src/cloudConsole/cloudConsole.ts
This fix addresses https://github.com/microsoft/vscode-azure-account/issues/959
Stop using `--ms-enable-electron-run-as-node` flag since it's no longer supported.
I reached out to the VS Code team for more clarification on this flag and what it does:
> The flag was added originally as a fix for an MSRC case reported against VS Code desktop application on macOS. The attack used the ELECTRON_RUN_AS_NODE mode to start VS Code application as a node process to execute malicious scripts from within an sandboxed application using NODE_REQUIRE env flags. Mac app sandbox disallows command line flags when launching external applications but does allow env variables hence the attack became possible. So this also provided a way for us to disable the attack by only the ELECTRON_RUN_AS_NODE mode be …
> Stop using `--ms-enable-electron-run-as-node` flag to fix launching Cloud Shell on macOS

- src/cloudConsole/cloudConsole.ts
This fix addresses https://github.com/microsoft/vscode-azure-account/issues/719
For some reason only on Linux (in my case Ubuntu desktop 22.04.2) `process.execPath` and `process.argv0` are different. We are using the `process.argv0` value as the shell args that start up the child process to control the custom cloud shell shell. And for linux, `/proc/self/exe` wasn't working, but when I change it to `process.execPath` it's happy.
I'd love for some info on this if anyone knows what's going on here.
on Linux:
on macOS:
> Use `process.execPath` instead of `process.argv0` to fix launching Cloud Shell on Linux

- src/cloudConsole/cloudConsole.ts
The diff is misleading. There aren't that many changes here. I think because of the whitespace changes...
I'll do my best to explain what's going on here:
The Azure Account behavior was to get all authenticated tenants that have >0 subscriptions and let the user pick if there's more than one. The current behavior is to get all tenants and let the user pick if there's more than one. I'd like to make the experience mimic that of Azure Account.
The new behavior is the same as Azure Account, however a shortcut step 1. has been added that wasn't present before.
1. We list all tenants, if we find only one, we select it.
2. If they have multiple tenants, we check which are authenticated and have at least one subscription, if there's only one, we select it. (If there are zero, we still select the …
> Improve tenant selection for cloud shell

- CHANGELOG.md
- package-lock.json
- package.json
We had to skip 0.9.3 because of a marketplace issue. I'm going to try to overwrite that release by bumping the version to 0.9.4.
> Prep for 0.9.4 release

- src/cloudConsole/cloudConsole.ts
Fixes #911 
We weren't properly handling sovereign clouds in the Cloud Shell when getting the session to use for the requests related to Cloud Shell.
My solution is to get the session from a subscription because that will handle getting a session for the proper tenant and sovereign cloud for us thanks to the auth package.
Since we're getting the session from the subscription, we now have a check for if the selected tenant has no subscriptions we don't continue. I confirmed with the cloud shell team that they don't plan on supporting cases where the user has no subscriptions.
> Fix Cloud Shell in sovereign clouds

- bin/node.bat
- bin/node.sh
- src/cloudConsole/cloudConsole.ts
Fixes #930 
Turns out somewhere in the new build pipeline we setup for signing some files are being rewritten with CRLF line endings instead of LF line endings. This caused the bash script we use to help fork the child process that cloud shell relies on to fail.
I've known for a while that we could get rid of these scripts so I just went ahead and made that change. IMO that's way easier than trying to figure out why the line endings are changing in our pipeline.
Other than removing the scripts, my goal was to keep all other behavior the same. As far as I can tell the .bat script wasn't being used.
> Stop using external bash script to start cloud shell

- src/commands/accounts/selectSubscriptions.ts
- src/commands/registerCommands.ts
This adds the ability to scope the select subscriptions prompt by tenant. It also adds the option to filter by account, but that's not implemented in this PR.
If a prompt is scoped to a tenant, it won't change any selected subscriptions that aren't in that tenant. Only subscriptions shown in the picker will be removed or added to the selected subscriptions setting.
> Add feature to scope select subscriptions prompt by tenant

- src/gitHubCopilotForAzure.ts
I forgot numbers show up weird in gdpr...
> Rename to `ghcpfa`

- package.json
- src/tree/azure/AzureResourceTreeDataProvider.ts
On first time sign in for accounts with multiple tenants, users will need to sign in to a specific tenant. [A customer pointed out that our clickable "Sign in to Directory..." tree item doesn't really look clickable](https://github.com/microsoft/vscode-azureresourcegroups/issues/899#issuecomment-2489498875). I agree, we can improve it by using a welcome view.
Here's the result:
Before:
After:
Steps to reproduce (need an account with multiple tenants to test):
1. Sign out of your account on the Azure Portal in your browser.
2. Close and reopen the browser
3. Sign out of all Microsoft accounts in VS Code
4. Sign in using the Azure Resources view "Sign in..." button
You should see the "sign in to tenant/directory" view now.
> Use welcome view for resources sign in to tenant state

- src/commands/accounts/selectSubscriptions.ts
- src/tree/tenants/TenantResourceTreeDataProvider.ts
- src/tree/tenants/registerTenantTree.ts
Cleaning up the unselected tenant logic. Ensuring there aren't duplicates in the momento.
> Fixup unselected tenant logic

- package.nls.json
We've received feedback that more users know it as tenants rather than directories. It was originally put as directory since that's what the portal uses. So now we'll use both.
> Improve signInToTenant command title

- package.json
- package.nls.json
- src/commands/registerCommands.ts
- src/tree/tenants/TenantResourceTreeDataProvider.ts
- src/tree/tenants/registerTenantTree.ts
> Add Tenant view telemetry and sign in button on tenant view 

- package-lock.json
- package.json
- src/services/VSCodeAzureSubscriptionProvider.ts
- test/api/MockAzureSubscriptionProvider.ts
> Upgrade to auth v4

- src/cloudConsole/cloudConsole.ts
Fixes https://github.com/microsoft/vscode-azureresourcegroups/issues/971
> Fix cloudShell pick tenant step

- src/tree/BranchDataItemCache.ts
- src/tree/BranchDataItemWrapper.ts
- src/tree/ResourceTreeDataProviderBase.ts
- src/tree/azure/AzureResourceItem.ts
- src/tree/azure/SubscriptionItem.ts
- src/tree/azure/grouping/GroupingItem.ts
- src/tree/azure/idPrefix.ts
- test/api/viewProperties.test.ts
Fixes #972
Add the `/accounts/<accountId>/tenants/<tenantId>` prefix to all items. This includes adding it to each item level in Resources: subscription items, grouping items, and resource items. Then I prefix all items provided by contributed branch data providers as well.
> Prefix all ids with account and tenant ids

- src/tree/ResourceTreeDataProviderBase.ts
When using the "Classic" Microsoft authentication implementation (vs. MSAL) there can be a slash in the account id. In this regex we assumed that wasn't the case.
This was making find tree item fail which is used by Function App deploy which was then failing.
> Fix finding items with slashes in the account id

- src/tree/BranchDataItemWrapper.ts
- src/tree/ResourceTreeDataProviderBase.ts
This breaks find item by id which causes issues in some extensions.
The bad ids look like: `/accounts/<accountId>/tenants/<tenantId>//subscriptions/<subscriptionId>/resourceGroups/...`
> Prevent tree item ids from having double slash

- src/commands/createResourceGroup.ts
- src/commands/deleteResourceGroup/v2/deleteResourceGroupV2.ts
- src/tree/TreeItemState.ts
- src/tree/azure/AzureResourceItem.ts
- src/tree/azure/SubscriptionItem.ts
- src/tree/azure/grouping/GroupingItem.ts
- src/tree/azure/grouping/ResourceGroupGroupingItem.ts
- src/tree/azure/idPrefix.ts
Fixes https://github.com/microsoft/vscode-azureresourcegroups/issues/1006
> Fix tree item state issues by adding account and tenant to ids

- src/gitHubCopilotForAzure.ts
Prevents the toast from showing up while the extension is still being installed in /azure
> Add 10 second delay before checking for ghc4a

- src/api/DefaultAzureResourceProvider.ts
- src/managedIdentity/ManagedIdentityItem.ts
- src/managedIdentity/RoleAssignmentsItem.ts
- src/managedIdentity/RoleDefinitionsItem.ts
- src/tree/GenericItem.ts
It was easier to convert the `GenericResources` to `DefaultAzureResources` to enable open in portal for them.
`RoleDefinitions` was easy enough to just build the portal url for.
> Allow service and target resources to openInPortal and add tooltips to role defintions

- package-lock.json
- package.json
- src/api/compatibility/pickAppResource.ts
Update utils to 2.6.2 to use the updated `registerCommand` function that records subscriptionId and resourceId automatically.
Also adds logic to `pickAppResource` (used by v1 extensions) to record subscriptionId and resourceId in telemetry
> Add subscriptionId and resourceId to telemetry

- package-lock.json
- package.json
- src/api/compatibility/pickAppResource.ts
Consume utils v2.6.3 https://github.com/microsoft/vscode-azuretools/releases/tag/microsoft-vscode-azext-utils-v2.6.3
I also put another try/catch in pickAppResource. I'm pretty sure no AzExtTreeItems that don't have subscriptions should ever make it to that code path, but better be safe than sorry.
Read more about the cause of the issues in https://github.com/microsoft/vscode-azuretools/pull/1918
Fixes #1080 and #1081
> Fix issues caused by telemetry change

- src/tree/azure/DefaultAzureResourceItem.ts
Just needed to give the "Install extension to enable additional features..." tree items unique ids to fix it.
Fixes #1051
> Fix duplicate id issue for Install extension tree items

- src/azureExtensions.ts
The `Mongo Clusters / MongoDB (vCore)` feature has been fully shipped in Azure Databases VS Code Extension, the development-stage feature flag is no longer required.
---
This pull request includes changes to the `src/azureExtensions.ts` file to remove temporary support for MongoClusters in the Azure Resources extension. The main changes involve deleting the temporary function and interface used for enabling MongoClusters support and simplifying the resource types configuration for the `vscode-cosmosdb` extension.
Removal of temporary MongoClusters support:
* [`src/azureExtensions.ts`](diffhunk://#diff-0b490ed3eaa957d1045b981a579531e30c3da11c04a02b3e41f5cb7bf77b3627L7-L32): Removed the `enableMongoClustersSupport` function and the `ExtensionPackageMongoClustersEnabled` interface.
* …
> Removed obsolete `mongoClusters` feature flag

- src/commands/revealResource.ts
This pull request adds the capability to the `revealResource` command to reveal deep resources beyond the known `ResourceGroupsItem` if the registered `BranchDataProvider` generates `TreeElementWithId` and implements `getParent()`.
As in `/subscriptions/[subscriptionId]/resourceGroups/[resourceGroup]/providers/Microsoft.DocumentDB/databaseAccounts/[accountName]/[databaseName]/[collectionName]` would no longer throw but rather `ResourceTreeDataProviderBase.findItemById` would properly find the nodes underneth the actual `/subscriptions/[subscriptionId]/resourceGroups/[resourceGroup]/providers/Microsoft.DocumentDB/databaseAccounts/[accountName]` resource and – if the custom `BranchDataProvider` properly implements `getParent()` – reveal the deep node.
Enhancements to resource ID parsing:
* …
> Allow revealResource to reveal deep resources beyond known ResourceGroupsItem

- src/azureExtensions.ts
Since AI Foundry extension has been published, remove the private option to enable the installation.
> Enable installing AI Foundry extension

- api/src/resources/resourcesApi.ts
- src/api/createAzureResourcesHostApi.ts
- src/api/createWrappedAzureResourcesExtensionApi.ts
- src/commands/revealResource.ts
This pull request introduces a new public API feature to reveal a resource in the Workspace tree view. Similar to `revealAzureResource` this allows revealing items inside the Workspaces tree view.
Key changes include:
* [`api/src/resources/resourcesApi.ts`](diffhunk://#diff-5ec3e559ee39317faa20c32e1239f1bc34e9cce5dd7772f2d25ac42d236aed3cR64-R71): Added a new method `revealWorkspaceResource` to the `ResourcesApi` interface to reveal a resource in the Workspace tree view.
* [`src/commands/revealResource.ts`](diffhunk://#diff-aaa5d95043f7e29bf55520ba7850496f6b19b76396e87953d2f998baf1b0505fR26-R36): Implemented the `revealWorkspaceResource` function to handle the logic for revealing a resource in the Workspace tree view.
* [`src/api/createAzureResourcesHostApi.ts`](diffhunk://#diff-cf399355933 …
> Add revealWorkspaceResource function to expose resources in Workspaces

- api/src/getAzExtResourceType.ts
- src/azureExtensions.ts
There is a new resource type for Azure AI Foundry projects. We need to list both type of projects in the tree view.
> feat: support new type of AI Foundry projects

- package.json
- package.nls.json
- src/chat/askAgentAboutActivityLog.ts
- src/chat/tools/GetAzureActivityLog/GetAzureActivityLog.ts
- src/chat/tools/GetAzureActivityLog/convertActivityTree.ts
- src/chat/tools/registerLMTools.ts
- src/commands/registerCommands.ts
- src/extension.ts
Keeping this first pass fairly simple.  This does not include custom command context yet.
Example of the view:
Clicking on the sparkle icon will open up the chat window with a special prompt to activate the LM tool which parses the entire raw activity log as json for use as copilot context. 
Expect a follow up PR to add more command context once this or similar gets added: https://github.com/microsoft/vscode-azuretools/pull/2005
> Hook up Copilot for the activity log and expose basic commands

- src/chat/askAgentAboutActivityLog.ts
- src/commands/createResourceGroup.ts
Closes #1182  
Suppress progress hides the progress.report messages, leaving only the live timer.
Also remove the initial open call for `askAgentAboutActivityLog`.  I thought this had fixed the issue where sometimes the chat is not refreshed, but the issue seems to still happen on occasion, so I'm removing the extra open call since it seems to have not fixed the issue.
> Suppress progress for `createResourceGroup` & remove unnecessary chat open call for copilot activity log

- api/CHANGELOG.md
- api/docs/vscode-azureresources-api.d.ts
- api/package-lock.json
- api/package.json
- api/src/resources/azure.ts
- api/src/vscode.proposed.authLearnMore.d.ts
- api/src/vscode.proposed.authenticationChallenges.d.ts
This is the first change that must be released in order to work towards closing https://github.com/microsoft/vscode-azureresourcegroups/issues/1200. This release will be consumed in utils.
Challenge support is currently a proposed api available in Insiders. It will be released in the next Stable release 1.104.
> api: Support challenges when getting sessions from VS Code

- api/package-lock.json
- api/package.json
Once I pinned the version in #1205  I didn't realize that it no longer satisfied the typings. I went back and found the actual version we need to fix it which is 1.93.
> api: require vscode 1.93 types

- package.json
For some reason, it wasn't in the package.json.
> Add authenticationChallenges to enabledApiProposals
