src/commands/tags/getTagDiagnostics.ts

Fixes https://github.com/microsoft/vscode-azureresourcegroups/issues/21

Show tag diagnostic if name is empty

---

package-lock.json
package.json
src/commands/tags/TagFileSystem.ts
src/tree/ResourceGroupTreeItem.ts
src/tree/SubscriptionTreeItem.ts
src/utils/azureClients.ts

Related to https://github.com/microsoft/vscode-azuretools/pull/806

Lazy load azure package

---

package-lock.json
package.json
src/commands/deleteResourceGroup.ts
src/commands/registerCommands.ts
src/commands/tags/TagFileSystem.ts
test/global.test.ts

Related to https://github.com/microsoft/vscode-azuretools/pull/820

Bump UI package

---

package-lock.json
package.json
test/global.test.ts

Bump shared packages

---

src/commands/deleteResourceGroup.ts

Fixes https://github.com/microsoft/vscode-azureresourcegroups/issues/40

it's -> its

---

src/commands/tags/TagFileSystem.ts

Fixes https://github.com/microsoft/vscode-azureresourcegroups/issues/54

Don't show "Insert tag name" in "View Properties"

---

src/commands/tags/TagFileSystem.ts
src/commands/tags/getTagDiagnostics.ts

Fixes https://github.com/microsoft/vscode-azureresourcegroups/issues/53
Fixes https://github.com/microsoft/vscode-azureresourcegroups/issues/18

Block on jsonc errors as well as our own Azure errors when editing tags

---

CHANGELOG.md
NOTICE.html

Will bump version after testing is done

Prep for release

---

package-lock.json
package.json
src/commands/helpAndFeedback/getStarted.ts
src/commands/helpAndFeedback/reportIssue.ts
src/commands/helpAndFeedback/reviewIssues.ts
test/global.test.ts

Same as https://github.com/microsoft/vscode-azurestorage/pull/987

Use action-specific user input

---

package-lock.json
package.json
src/commands/openInPortal.ts
src/commands/registerCommands.ts
src/commands/tags/TagFileSystem.ts
src/tree/ResourceGroupTreeItem.ts
src/tree/ResourceTreeItem.ts
src/tree/SubscriptionTreeItem.ts
src/utils/azureClients.ts

See https://github.com/microsoft/vscode-azuretools/pull/963 for more info

Bump UI package to support correlation id

---

src/extension.ts
src/extensionVariables.ts
src/tree/ResolvableTreeItem.ts
src/tree/SubscriptionTreeItem.ts
src/utils/ExtensionActivationManager.ts

Re-created #116 with unified as the base branch.
I implemented the activation manager and tested with SWA and it works great!
https://github.com/microsoft/vscode-azureresourcegroups/blob/dc78b6d95b604feea27662da8c7537503470e9c4/src/tree/SubscriptionTreeItem.ts#L57
https://github.com/microsoft/vscode-azureresourcegroups/blob/dc78b6d95b604feea27662da8c7537503470e9c4/src/tree/ResolvableTreeItem.ts#L57

Add activation manager

---

src/api/registerApplicationResourceProvider.ts
src/api/registerApplicationResourceResolver.ts
src/tree/AppResourceTreeItem.ts

Minor updates

---

src/utils/ExtensionActivationManager.ts

The VSCode team recommended we use a custom contribution point rather than custom activation event. This makes that change.
Sample contribution point:
```json
"x-azResources": {
"activation": {
"onFetch": [
"microsoft.web/staticsites"
]
}
}
```

Change activation manager to use contribution point

---

src/tree/AppResourceTreeItem.ts

Makes `instanceof Proxy` return `AzExtTreeItem` or `AzExtParentTreeItem` depending on if `loadMoreChildrenImpl` is defined on the resolve result.
Instead of removing any usages of `instanceof` in the utils and azureutils packages, I think this solution is good until we have a better understanding of what (if any) changes to `AzExtTreeItem` we're planning to make. Ex: make it an interface instead of an abstract class.
Other solutions explored:
Replacing uses of `instanceof` with:
```ts
function isAzExtTreeItem(item: unknown): item is AzExtTreeItem {
return (item as AzExtTreeItem).contextValue !== undefined;
}
```
Issue with this is picking a property to base the check on is bug prone. As long as `item` has `contextValue` defined, it'll pass this check. Whereas `instanceof` actually checks …

Fix Proxy instanceof

---

src/azureExtensions.ts

Fixes https://github.com/microsoft/vscode-azurecontainerapps/issues/82

Add container apps to list of azureExtensions

---

src/tree/ResourceGroupTreeItem.ts
src/tree/SubscriptionTreeItem.ts

Fixes a maximum call stack size exceeded error

Fix creating RG

---

.github/workflows/version-check.yml
package-lock.json
package.json

Enforces PRs to bump the version.
The GitHub Action used doesn't have any dependencies https://github.com/kriasoft/check-version/blob/master/main.js

Add version check action

---

package-lock.json
package.json
src/commands/explorer/focusGroup.ts
src/tree/GroupTreeItemBase.ts
src/tree/SubscriptionTreeItem.ts

Fix focus this group command when used from palette #191
Also fixes https://github.com/microsoft/vscode-azurestaticwebapps/issues/667
https://user-images.githubusercontent.com/12476526/164555132-e86d8dd5-c00b-4fa8-be88-755faa829159.mov

Fix focus this group command when used from palette

---

package-lock.json
package.json
src/tree/SubscriptionTreeItem.ts

Depends on https://github.com/microsoft/vscode-azuretools/pull/1146
> Needed to support some database scenarios where the resources can only be differentiated based on tag values.

Handle filtering by tag

---

package-lock.json
package.json
src/activityLog/ActivityTreeItem.ts
src/api/pickAppResource.ts
src/extension.ts
src/resolvers/ShallowResourceResolver.ts
src/tree/GroupTreeItemBase.ts
src/tree/ResolvableTreeItemBase.ts
src/tree/SubscriptionTreeItem.ts

Along with https://github.com/microsoft/vscode-azuretools/pull/1150, this is an alternative to https://github.com/microsoft/vscode-azuretools/pull/1148 and #223.
Depends on https://github.com/microsoft/vscode-azuretools/pull/1150.

Resolve when group node is expanded

---

package-lock.json
package.json
package.nls.json
src/commands/createResource.ts

Here's how it looks
Matt you're a 🧙 🪄 . I really like all the descriptions.

Allow extensions to provide detail to the create commands

---

package-lock.json
package.json
src/tree/ResolvableTreeItemBase.ts

Depends on https://github.com/microsoft/vscode-azuretools/pull/1156
Alternative to #230 
Here's how it looks:
https://user-images.githubusercontent.com/12476526/167943950-06bb1765-9062-45ac-beac-43d2b18fe972.mov

Fix double spinners

---

package-lock.json
package.json

Change default grouping to resourceType

---

package-lock.json
package.json
src/extension.ts

Improve view titles

---

package-lock.json
package.json
src/tree/SubscriptionTreeItem.ts

Fixes https://github.com/microsoft/vscode-azurevirtualmachines/issues/321

Make findAppResourceByResourceId case insensitive

---

package-lock.json
package.json
src/tree/SubscriptionTreeItem.ts

Fixes https://github.com/microsoft/vscode-azurefunctions/issues/3170

Make pickAppResource case insensitive

---

package-lock.json
package.json
src/extension.ts

Don't suppress resolve telemetry or error messages

---

package-lock.json
package.json
src/commands/registerCommands.ts

Fixes https://github.com/microsoft/vscode-azuretools/issues/1155
Also bumps azure utils to add Azure for Students node.

Register openUrl command, update azureutils

---

package-lock.json
package.json
src/tree/SubscriptionTreeItem.ts

Maintain focus on refresh

---

package-lock.json
package.json

So when we add buttons to this view title from other extensions in the future, we don't have to update RGs

Ensure refresh workspace button is the rightmost button

---

CHANGELOG.md
NOTICE.html
package-lock.json
package.json

- Bump version
- Update CHANGELOG
- Update NOTICE

Release v0.5.2 prep

---

package-lock.json
package.json

Upgrade utils package to fix duplicate element error

---

package-lock.json
package.json
src/commands/createResource.ts

Pass node to picked create command

---

package-lock.json
package.json
src/extension.ts

Enable canSelectMany for workspace tree view

---

package-lock.json
package.json

Make Resources and Workspace view visible by default

---

package-lock.json
package.json

Make location of "Edit Tags..." item consistent

---

package-lock.json
package.json
src/tree/SubscriptionTreeItem.ts

pickAppResource sort by name

---

package-lock.json
package.json

Fixes #296
[View changelog](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/resources/arm-resources-profile-2020-09-01-hybrid/CHANGELOG.md#200-2022-03-08)

Upgrade 2020-09-01-hybrid sdk to T2

---

package.json

Fixes https://github.com/microsoft/vscode-azureresourcegroups/issues/343

Update min version of VS Code to 1.65.0

---

package-lock.json
package.json
src/tree/SubscriptionTreeItem.ts

Fixes https://github.com/microsoft/vscode-azurefunctions/issues/3210
Also went ahead and updated utils package

Throw NoResourceFoundError

---

src/azureExtensions.ts
src/utils/azureUtils.ts

Related to:  https://github.com/microsoft/vscode-azurecontainerapps/pull/170

Container Apps Integration Prep

---

package.json
src/api/v2/compatibility/CompatibleAzExtTreeDataProvider.ts
src/extension.ts
src/tree/v2/ResourceBranchDataProviderManagerBase.ts
src/tree/v2/ResourceTreeDataProviderBase.ts
src/tree/v2/application/registerResourceGroupsTreeV2.ts
src/tree/v2/workspace/registerWorkspaceTreeV2.ts

Fixes compatibility issues with client extensions using the TDP.
* subscription node fetched via `showTreeItemPicker`
* `refresh`

Use `CompatibleAzExtTreeDataProvider`

---

package.json
src/tree/v2/application/registerResourceGroupsTreeV2.ts
src/tree/v2/workspace/registerWorkspaceTreeV2.ts

Change view Ids to match V1 (#408)

---

src/tree/v2/application/ApplicationResourceTreeDataProvider.ts

It looks like some early VS Code authentication investigative work was still being used (and causing spurious user prompts); we should route authentication token requests to the original Azure Account credentials; we're not intending to bypass Azure Account quite yet.

Use Azure Account auth for now.

---

src/api/v2/ResourceProviderManagers.ts
src/api/v2/v2AzureResourcesApiImplementation.ts
src/extension.ts
src/tree/v2/azure/AzureResourceTreeDataProvider.ts
src/tree/v2/azure/SubscriptionItem.ts
src/tree/v2/azure/registerResourceGroupsTreeV2.ts

Missed this class in the other PR.

Rename Application -> Azure provider manager

---

src/tree/v2/BranchDataItemCache.ts
src/tree/v2/ResourceTreeDataProviderBase.ts

Rename method to `clear`

---

src/tree/v2/ResourceTreeDataProviderBase.ts
src/tree/v2/azure/AzureResourceTreeDataProvider.ts

Suggested in https://github.com/microsoft/vscode-azureresourcegroups/pull/358#discussion_r1019557307

Don't expose `EventEmitter`

---

hostapi.v2.internal.d.ts
package-lock.json
package.json
src/api/AzureResourceGroupsExtensionApi.ts
src/api/registerApplicationResourceResolver.ts
src/api/registerWorkspaceResourceProvider.ts
src/api/v2/createAzureResourcesHostApi.ts
src/api/v2/v2AzureResourcesApiWrapper.ts
src/extension.ts
src/extensionVariables.ts

Depends on https://github.com/microsoft/vscode-azuretools/pull/1300, will merge when released.

Update v2 typings

---

src/api/v2/ResourceGroupsExtensionManager.ts

Use `x-azResources` key instead of `x-azResourcesV2` to look for contributions. We don't need to distinguish between v1 and v2 here, and I'll update the client extensions to reflect this change.
Also changing the `application` part to `azure`.

Update contribution keys

---

src/commands/tags/TagFileSystem.ts
src/tree/v2/azure/AzureResourceGroupingManager.ts
src/tree/v2/azure/GroupingItem.ts

Fixes #468, and fixes editing tags for a resource group

Fix Edit Tags and View Properties commands for resource groups

---

src/api/v2/compatibility/CompatibleAzExtTreeDataProvider.ts
src/api/v2/compatibility/CompatibleAzureAccountTreeItem.ts

Fixes https://github.com/microsoft/vscode-azureresourcegroups/issues/485

Add CompatibleAzureAccountTreeItem

---

src/commands/createResourceGroup.ts
src/tree/v2/azure/SubscriptionItem.ts

Add subscription property to SubscriptionItem for compatibility

---

package-lock.json
package.json
src/api/v2/compatibility/CompatibleAzExtTreeDataProvider.ts

Depends on https://github.com/microsoft/vscode-azuretools/pull/1332
Fixes https://github.com/microsoft/vscode-azureresourcegroups/issues/489, and also fixes the add binding command

Implement showTreeItemPicker compat shim

---

package.json
src/commands/registerCommands.ts

Working towards fixing https://github.com/microsoft/vscode-azureresourcegroups/issues/487.

Add dedicated commands for refreshing entire tree

---

src/utils/v2/credentialsUtils.ts

Fixes https://github.com/microsoft/vscode-azureresourcegroups/issues/472

Define subscriptionDisplayName property

---

src/commands/openInPortal.ts
src/tree/azure/AzureResourceItem.ts
src/tree/azure/DefaultAzureResourceItem.ts
src/tree/azure/GroupingItem.ts
src/tree/azure/SubscriptionItem.ts
src/utils/v2/createPortalUrl.ts

Fix Open in Portal for subscriptions and RGs

---

src/commands/viewProperties.ts

Fix view properties from command palette

---

package-lock.json
package.json
src/api/ResourceProviderManagers.ts
src/api/compatibility/workspace/CompatibilityWorkspaceResourceProvider.ts
src/tree/workspace/WorkspaceResourceTreeDataProvider.ts

Depends on https://github.com/microsoft/vscode-azuretools/pull/1342
Fixes https://github.com/microsoft/vscode-azureresourcegroups/issues/507

Simplify workspace resource provider

---

src/commands/tags/editTags.ts

Fix invoking edit tags from command palette

---

package-lock.json
package.json
src/commands/explorer/groupBy.ts

Implement Group By Arm Tag command

---

src/api/DefaultAzureResourceProvider.ts
src/commands/deleteResourceGroup/v2/deleteResourceGroupV2.ts

Fixes #526 
Also added some telemetry to this method. If this keeps happening we'll be able to give the telemetry to the service team.

Dedupe Azure resources

---

src/tree/ResourceBranchDataProviderManagerBase.ts

Reverts microsoft/vscode-azureresourcegroups#531
See https://github.com/microsoft/vscode-azureresourcegroups/pull/531#issuecomment-1404268426
😢

Revert "Scoped global refresh for BDPs"

---

src/api/createWrappedAzureResourcesExtensionApi.ts
src/tree/ResourceBranchDataProviderManagerBase.ts
src/utils/wrapFunctionsInTelemetry.ts

Wraps client provided `BranchDataProvider`s in telemetry.

Wrap BranchDataProviders in telemetry

---

package-lock.json
package.json

Fixes https://github.com/microsoft/vscode-azurestorage/issues/1205

Upgrade utils to 0.4.3

---

src/api/compatibility/CompatibleAzExtTreeDataProvider.ts
src/tree/ResourceTreeDataProviderBase.ts

Fixes https://github.com/microsoft/vscode-azurestorage/issues/1208
Fixes https://github.com/microsoft/vscode-azurestorage/issues/1206

Fix v1.5 client tree item refreshing

---

src/api/compatibility/CompatibleAzExtTreeDataProvider.ts
src/extension.ts

Fixes https://github.com/microsoft/vscode-azurestorage/issues/1209

Fix load more

---

extension.bundle.ts
test/api/isWrapper.test.ts

Lost when we moved the wrapper utils to this repo from tools
also credit to Brandon for writing these tests originally

Add isWrapper tests

---

src/tree/BranchDataProviderItem.ts

In order to share them with the tests

Make BranchDataItemWrapper context values static

---

src/commands/deleteResourceGroup/v2/deleteResourceGroupV2.ts

Sort resource group picks

---

src/commands/createResourceGroup.ts
src/tree/ResourceTreeDataProviderBase.ts

Fix refreshing subscription after creating a RG

---

package.json

Remove (V2) label from view titles

---

api/CHANGELOG.md
api/README.md
api/package.json

Also updated the changelog and bumped the version to prepare for a release

Polish API package readme 

---

.vscode/launch.json
package-lock.json
package.json
src/tree/azure/registerAzureTree.ts
src/tree/workspace/registerWorkspaceTree.ts

Fixes https://github.com/microsoft/vscode-azureresourcegroups/issues/595
There's a weird VS Code dev bug that doesn't like getting the title from our package.json. No idea why it's only impacting these two labels-- I'd assume it has something to do with the other options we are passing in. But this seems like the easiest fix for it for now.

Add title properties to tree views

---

main.js
src/tree/workspace/registerWorkspaceTree.ts

Add title property to workspace tree

---

src/tree/azure/registerAzureTree.ts
src/tree/createTreeView.ts
src/tree/workspace/registerWorkspaceTree.ts

Just a small refactor. We already handled setting the description in this helper so we can set title too.

Set tree view title in `createTreeView`

---

src/commands/deleteResourceGroup/v2/deleteResourceGroupV2.ts

Throw a no resource found error if there are no resource groups

---

src/services/WebAzureSubscriptionProvider.ts

Update `selectSubscription` to prompt for sign-in

---

src/tree/BranchDataItemCache.ts

Minimal changes required to fix createClient issue. Fixes https://github.com/microsoft/vscode-azureresourcegroups/issues/640

Fix createClient issue

---

README.md

Add a small blurb about VSCode.dev

---

src/api/compatibility/application/CompatibleApplicationResourceTreeItem.ts
src/commands/tags/TagFileSystem.ts
src/extension.ts
src/services/DesktopSubscriptionProvider.ts
src/services/SubscriptionProvider.ts
src/tree/azure/AzureResourceGroupingManager.ts
src/utils/wrapFunctionsInTelemetry.ts
test/api/MockAzureAccountApi.ts
test/getTagDiagnostics.test.ts
tsconfig.json

All changes are typings only. But please check my work to make sure.

Enable strict mode and update typings

---

CHANGELOG.md
package-lock.json
package.json

https://github.com/microsoft/azcode-internal/issues/7

Bump version and update change log for v0.7.1 release

---

package-lock.json
package.json
src/extension.ts
src/extensionVariables.ts

Depends on https://github.com/microsoft/vscode-azuretools/pull/1440
yay logs. plus it redacts things for us

Setup @azure/logger using `setupAzureLogger` util

---

package.json
package.nls.json
src/commands/focus/focusGroup.ts
src/constants.ts
src/tree/azure/GroupingItem.ts

https://github.com/microsoft/vscode-azureresourcegroups/assets/12476526/1122c399-fcc1-412b-9d2b-2ebd8682ba7a

Support focus/unfocus group from command palette

---

package-lock.json
package.json
src/commands/accounts/logIn.ts
src/commands/accounts/selectSubscriptions.ts
src/tree/azure/AzureResourceTreeDataProvider.ts
src/tree/azure/AzureResourceTreeDataProviderBase.ts

Spinner when signing in (fixes https://github.com/microsoft/vscode-azureresourcegroups/pull/707#discussion_r1273953608):
And removes that test line where I was printing to console. https://github.com/microsoft/vscode-azureresourcegroups/pull/707#discussion_r1273954262
Also fixes #729

Fix remaining issues from #707

---

api/README.md
package-lock.json
package.json
src/commands/createResource.ts
src/utils/azureUtils.ts
src/utils/treeUtils.ts

Added it to Functions to try out:

Support icons next to create commands in quick pick

---

api/CHANGELOG.md
api/docs/vscode-azureresources-api.d.ts
api/package-lock.json
api/package.json
api/src/getAzExtResourceType.ts
api/src/index.ts
src/api/compatibility/pickAppResource.ts

See https://github.com/microsoft/vscode-azuretools/pull/1571 for more details

Add `getAzExtResourceType` function

---

api/README.md
api/docs/vscode-azureresources-api.d.ts
api/src/AzExtResourceType.ts
api/src/getAzExtResourceType.ts

We'll map it to an upcoming extension later, when it's ready.

Add `ArcEnabledServers` resource to `AzExtResourceType` enum 

---

package-lock.json
package.json

Upstream issue: https://github.com/microsoft/vscode-azuretools/issues/1607

Update auth package to v1.2.2 to fix sign in issue

---

package-lock.json
package.json
package.nls.json
src/commands/registerCommands.ts

Fixes https://github.com/microsoft/vscode-azureresourcegroups/issues/750

Add Sign in to Directory command

---

package-lock.json
package.json
test/api/MockAzureSubscriptionProvider.ts

Depends on https://github.com/microsoft/vscode-azuretools/pull/1627. Need to also actually release that version of the package.

Fix sovereign clouds and do `npm audit fix`

---

CHANGELOG.md
package-lock.json
package.json

Megan and I tested zip deploy works on Windows and macOS. And I also tested that it fixes https://github.com/microsoft/vscode-azureresourcegroups/issues/768#issuecomment-1855895035.

Prep for 0.8.3 release

---

.azure-pipelines/1esmain.yml

Add 1ES Pipeline

---

.vscode/launch.json
api/src/AzExtResourceType.ts
api/src/getAzExtResourceType.ts
resources/azureIcons/WebPubSub.svg
src/azureExtensions.ts
src/utils/azureUtils.ts

Extension for [Azure Web PubSub service](https://azure.microsoft.com/en-us/products/web-pubsub) is under developing.
Add basic integration for it.

Basic integration for Azure Web PubSub Service

---

.azure-pipelines/1esmain.yml

Add parameter to manually enable long running tests

---

package.json

Fix Azure view keybinding on Windows

---

.github/workflows/feature-request.yml

They added these new required parameters here https://github.com/microsoft/vscode-github-triage-actions/pull/271/files#

Fix feature-request action

---

src/tree/TreeItemState.ts

Descriptions on subscription items weren't showing up for Megan and I found out why.

Fix tree item descriptions

---

api/CHANGELOG.md
api/docs/vscode-azureresources-api.d.ts
api/package-lock.json
api/package.json
api/src/resources/azure.ts
package-lock.json
package.json

Somehow none of my changes were saved last time. Not sure how it all got reset but it works out because I accidentally called it `getSessionForScopes` instead of `WithScopes`. I keep confusing the two names.

Update Resources API to include `AzureAuthentication.getSessionWithScopes`

---

api/CHANGELOG.md
api/package-lock.json
api/package.json

Releasing the changes from #894

api: Bump version and update changelog

---

.azure-pipelines/1esmain.yml
.azure-pipelines/SignExtension.signproj
SignExtension.signproj

See https://github.com/microsoft/vscode-azuretools/pull/1775 for context.

Sign with MSBuild

---

src/commands/revealResource.ts

We can merge this PR after the currently planned release

Improvements to error masking

---

src/commands/cloudShell.ts

We mask all urls so I'm going to not record the url and record the repository name and author instead.

Telemetry fix

---

src/commands/accounts/selectSubscriptions.ts

Requested by the `@azure` team
cc: @MRayermannMSFT

Enable scoping selectSubscriptions command by account

---

src/tree/azure/SubscriptionItem.ts

Fix opening subscriptions in the portal 

---

src/tree/azure/grouping/ResourceGroupGroupingItem.ts

Fixup resource group grouping items

---

package.json

Updated Disambiguation descriptions to enable intent detection for @azure for the following prompts: How do I create an Azure function?
do static web apps support static ip addresses?
Design a strategy for migrating on-premises SQL Server databases to Azure SQL Managed Instance. Analyze my project and recommend Azure services for me. Where is GPT-4o mini available using subscription cda6aeab-6dec-4567-a4d8-3770583a13f0

Updated Disambiguations to improve intent detection for @azure

---

package.json

Reverts microsoft/vscode-azureresourcegroups#1061
Reverting as we suspect change has contributed to intent detection drop

Revert "Updated Disambiguations to improve intent detection for @azure"

---

src/cloudConsole/cloudConsole.ts

Fix outdated string in cloud shell logs

---

main.js

Fixes https://github.com/microsoft/vscode-azureresourcegroups/issues/1082
Confirmed that is showing up now.

Add /* ignoreBundle */ so replace will work on gulp task

---

src/commands/revealResource.ts

#1108 forgot to add this import statement

Fixup import

---

src/tree/activityLog/ActivityItem.ts
src/tree/activityLog/ActivityLogBranchDataProvider.ts

Also expanding the tree node automatically. We need it for the steps-- we can figure out how to actually check for it later, but it's necessary for 90% of the commands anyway,

Have a backwards compat shim for the activity log view

---

package-lock.json
package.json

Uses an outdated reference to `form-data`

Remove unused dependency `@azure/ms-rest-js`

---

src/cloudConsole/cloudShellChildProcess/cloudConsoleLauncher.ts

Fixes https://codeql.microsoft.com/issues/ecaa9c95-1593-42a6-8a45-e906b311114e?copilot_promptid=E91B0CE9-0C1B-4AC2-8A46-33F49B67E058

Suppress CodeQL alert

---

api/CHANGELOG.md
api/docs/vscode-azureresources-api.d.ts
api/package-lock.json
api/package.json
api/src/resources/azure.ts
api/src/vscode.proposed.authenticationChallenges.d.ts

Corresponding to https://github.com/microsoft/vscode/pull/265921. Very similar to #1215.

api: Adjust to changes in typings

---

CHANGELOG.md
package-lock.json
package.json

Pull in changelog and bump package
